version: "3"
name: paper_assessment

services:
  api:
    build:
      context: ./
      dockerfile: docker/api/Dockerfile
    environment:
      - PORT=5000
    volumes:
      - ./:/app
    networks:
      - microservice_network

  disburse_service:
    build:
      context: ./
      dockerfile: docker/disburse/Dockerfile
    volumes:
      - ./:/app
    networks:
      - microservice_network

  transaction_service:
    build:
      context: ./
      dockerfile: docker/transaction/Dockerfile
    volumes:
      - ./:/app
    networks:
      - microservice_network

  trasnsaction-db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trasnsaction
    ports:
      - 5433:5432

  wallet_service:
    build:
      context: ./
      dockerfile: docker/wallet/Dockerfile
    volumes:
      - ./:/app
    networks:
      - microservice_network
    depends_on:
      - wallet-db

  wallet-db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wallet
    ports:
      - 5432:5432

  rabbit-mq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672 # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    restart: always
    networks:
      - microservice_network

networks:
  microservice_network:
    driver: bridge
